version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - revive
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
