name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: praetorian-inc/public-workflows/.github/workflows/go-ci.yml@3dcf34cfbe5e1332d490d28ed1bd119cd86cf81b  # v2.0.13
    permissions:
      contents: read
    with:
      build-cmd-path: ./cmd/vespasian
      build-binary-name: vespasian
      build-cgo-enabled: "1"
      build-matrix-os: '["linux"]'
      build-matrix-arch: '["amd64"]'
    secrets: inherit
