name: External Contribution Notify

on:
  issues:
    types: [opened, assigned, closed]
  pull_request_target:
    types: [opened, assigned, closed]

jobs:
  notify:
    uses: praetorian-inc/public-workflows/.github/workflows/external-contrib-notify.yml@faa2e42989736cf9b3f47e5377dd5f2e0327517f  # v2.0.2
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets: inherit
