name: Leaderboard Metrics

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  metrics:
    uses: praetorian-inc/public-workflows/.github/workflows/leaderboard-metrics.yml@c351826e6de27cadeb5b32ce81157355b283518b # v2.16.3
    with:
      capability_map: '[{"path": ".", "name": "vespasian"}]'