name: Leaderboard Metrics

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  metrics:
    uses: praetorian-inc/public-workflows/.github/workflows/leaderboard-metrics.yml@96b68220af4797b2bfe5be07183f6190f739e424 # v2.16.13
    with:
      capability_map: '[{"path": ".", "name": "vespasian"}]'